<figure>
<center>
<img src='https://www.economicas.uba.ar/wp-content/uploads/2020/08/cropped-logo_FCE.png' />
</figure>

# Introducción a JSON
**Taller de Programación para el Análisis de Datos — FCE-UBA**

JSON (*JavaScript Object Notation*) es un formato de texto plano para el intercambio de datos. Es independiente del lenguaje de programación y es el formato más usado en APIs.

---

## 1. ¿Qué es JSON?

JSON nació como parte de JavaScript, pero hoy es un estándar universal (RFC 8259). Sus ventajas:

- **Legible** por humanos y máquinas
- **Liviano** comparado con XML
- **Nativo** en APIs, bases de datos NoSQL, archivos de configuración
- **Soportado** en todos los lenguajes modernos

Un JSON es siempre **texto plano** — lo que viaja entre un servidor y un cliente es simplemente una cadena de caracteres.

---
## 2. Tipos de datos en JSON

JSON admite exactamente **6 tipos de valores**:

| Tipo | Ejemplo |
|------|--------|
| String | `"Juan Pérez"` |
| Number | `45000.50` |
| Boolean | `true` / `false` |
| Null | `null` |
| Array | `["Python", "SQL", "Excel"]` |
| Object | `{"clave": "valor"}` |

> ⚠️ Las cadenas siempre con **comillas dobles** (`"`). Las simples no son JSON válido.

---
## 3. Sintaxis: un empleado como JSON

La unidad básica es el **objeto**: un conjunto de pares `"clave": valor` entre llaves `{}`.

In [7]:
str_json_ej1='''{
  "id": 101,
  "nombre": "Laura Gómez",
  "departamento": "Tecnología",
  "salario": 145000,
  "activo": true,
  "jefe": null,
  "habilidades": [ "Python", "SQL",  "Git" ],
  "domicilio": {
    "ciudad": "Buenos Aires",
    "calle": "Av Córdoba",
    "altura": 1234,
    "codigo_postal": "C1425"
  }
}'''

print(str_json_ej1)

{
  "id": 101,
  "nombre": "Laura Gómez",
  "departamento": "Tecnología",
  "salario": 145000,
  "activo": true,
  "jefe": null,
  "habilidades": [ "Python", "SQL",  "Git" ],
  "domicilio": {
    "ciudad": "Buenos Aires",
    "calle": "Av Córdoba",
    "altura": 1234,
    "codigo_postal": "C1425"
  }
}

---
## 4. El módulo `json` de Python

Python convierte entre diccionarios y texto JSON con dos funciones clave:

| Función | Dirección | Mnemónico |
|---------|-----------|----------|
| `json.dumps()` | dict → string JSON | **dump** *to* **s**tring |
| `json.loads()` | string JSON → dict | **load** *from* **s**tring |
| `json.dump()` | dict → archivo | dump to file |
| `json.load()` | archivo → dict | load from file |

In [10]:
import json

dic_json_ej1=json.loads(str_json_ej1)
print(dic_json_ej1)
print(type(dic_json_ej1))

{'id': 101, 'nombre': 'Laura Gómez', 'departamento': 'Tecnología', 'salario': 145000, 'activo': True, 'jefe': None, 'habilidades': ['Python', 'SQL', 'Git'], 'domicilio': {'ciudad': 'Buenos Aires', 'calle': 'Av Córdoba', 'altura': 1234, 'codigo_postal': 'C1425'}}
<class 'dict'>

In [11]:
# En Python, el equivalente de un objeto JSON es un diccionario
empleado = {
    "id": 101,
    "nombre": "Laura Gómez",
    "departamento": "Tecnología",
    "salario": 145000,
    "activo": True,
    "jefe": None,                        # null en JSON
    "habilidades": ["Python", "SQL", "Git"],  # array
    "domicilio": {                        # objeto anidado
        "ciudad": "Buenos Aires",
        "calle" : "Av Córdoba",
        "altura" : 1234,
        "codigo_postal": "C1425"
    }
}

print(type(empleado))
print(empleado)

<class 'dict'>
{'id': 101, 'nombre': 'Laura Gómez', 'departamento': 'Tecnología', 'salario': 145000, 'activo': True, 'jefe': None, 'habilidades': ['Python', 'SQL', 'Git'], 'domicilio': {'ciudad': 'Buenos Aires', 'calle': 'Av Córdoba', 'altura': 1234, 'codigo_postal': 'C1425'}}

In [ ]:
import json

# ── dict → texto JSON ──────────────────────────────────────────
texto_json = json.dumps(empleado, ensure_ascii=False, indent=2)   #ensure_ascii=False Obliga a Python a escribir los caracteres especiales (como acentos, eñes o emojis) tal cual son, en lugar de codificarlos
#texto_json = json.dumps(empleado, ensure_ascii=False)

print(type(texto_json))   # <class 'str'>
print()
print(texto_json)

<class 'str'>

{
  "id": 101,
  "nombre": "Laura Gómez",
  "departamento": "Tecnología",
  "salario": 145000,
  "activo": true,
  "jefe": null,
  "habilidades": [
    "Python",
    "SQL",
    "Git"
  ],
  "domicilio": {
    "ciudad": "Buenos Aires",
    "calle": "Av Córdoba",
    "altura": 1234,
    "codigo_postal": "C1425"
  }
}

In [20]:
# ── texto JSON → dict ──────────────────────────────────────────
# Simulamos recibir un string (como si llegara de una API)
json_recibido = '{"id": 202, "nombre": "Carlos Ruiz", "salario": 98000, "activo": true}'

empleado2 = json.loads(json_recibido)

print(type(empleado2))    # <class 'dict'>
print(empleado2)
print(f"Nombre: {empleado2['nombre']}, Salario: ${empleado2['salario']:,}")

<class 'dict'>
{'id': 202, 'nombre': 'Carlos Ruiz', 'salario': 98000, 'activo': True}
Nombre: Carlos Ruiz, Salario: $98,000

---
## 5. Array de empleados: lista de objetos JSON

In [21]:
# Un array JSON es una lista de Python
empleados = [
    {"id": 1, "nombre": "Ana Torres",    "departamento": "Ventas",     "salario": 92000,  "nivel": "Senior"},
    {"id": 2, "nombre": "Bruno Sánchez", "departamento": "Tecnología", "salario": 155000, "nivel": "Semi"},
    {"id": 3, "nombre": "Carla Méndez",  "departamento": "RRHH",       "salario": 78000,  "nivel": "Junior"},
    {"id": 4, "nombre": "Diego López",   "departamento": "Finanzas",   "salario": 130000, "nivel": "Senior"},
    {"id": 5, "nombre": "Elena Ríos",    "departamento": "Tecnología", "salario": 175000, "nivel": "Senior"},
]

print(json.dumps(empleados, ensure_ascii=False, indent=2))

[
  {
    "id": 1,
    "nombre": "Ana Torres",
    "departamento": "Ventas",
    "salario": 92000,
    "nivel": "Senior"
  },
  {
    "id": 2,
    "nombre": "Bruno Sánchez",
    "departamento": "Tecnología",
    "salario": 155000,
    "nivel": "Semi"
  },
  {
    "id": 3,
    "nombre": "Carla Méndez",
    "departamento": "RRHH",
    "salario": 78000,
    "nivel": "Junior"
  },
  {
    "id": 4,
    "nombre": "Diego López",
    "departamento": "Finanzas",
    "salario": 130000,
    "nivel": "Senior"
  },
  {
    "id": 5,
    "nombre": "Elena Ríos",
    "departamento": "Tecnología",
    "salario": 175000,
    "nivel": "Senior"
  }
]

---
## 6. Anidamiento: objetos dentro de objetos

In [23]:
# Estructura anidada: empleado con historial y contacto
empleado_completo = {
    "id": 1,
    "nombre": "Ana Torres",
    "contacto": {
        "email": "ana.torres@empresa.com",
        "telefono": "+54 11 1234-5678"
    },
    "puesto": {
        "titulo": "Gerente de Ventas",
        "departamento": "Ventas",
        "nivel": "Senior"
    },
    "historial_salario": [
        {"anio": 2022, "salario": 78000},
        {"anio": 2023, "salario": 85000},
        {"anio": 2024, "salario": 92000}
    ],
    "habilidades": ["negociación", "CRM", "Excel", "liderazgo"]
}

# Acceso encadenado
print("Email:",    empleado_completo['contacto']['email'])
print("Título:",   empleado_completo['puesto']['titulo'])
print("Habilidad:", empleado_completo['habilidades'][0])

# Salario del último año del historial
ultimo = empleado_completo['historial_salario'][-1]
print(f"Salario {ultimo['anio']}: ${ultimo['salario']:,}")

Email: ana.torres@empresa.com
Título: Gerente de Ventas
Habilidad: negociación
Salario 2024: $92,000

---
## 7. Leer y escribir archivos `.json`

In [ ]:
# ── Escribir a archivo ─────────────────────────────────────────
archivo_json= open('empleados.json', 'w', encoding='utf-8')

json.dump(empleados, archivo_json, ensure_ascii=False, indent=2)

archivo_json.close()

print("Archivo guardado: empleados.json")

Archivo guardado: empleados.json

In [ ]:
# ── Leer desde archivo ─────────────────────────────────────────
archivo_json_empleados=open('empleados.json', 'r', encoding='utf-8')

datos_empleados = json.load(archivo_json_empleados)

archivo_json_empleados.close()

print(type(datos_empleados))
print(f"Total empleados: {len(datos_empleados)}")
print(datos_empleados[0])

<class 'list'>
Total empleados: 5
{'id': 1, 'nombre': 'Ana Torres', 'departamento': 'Ventas', 'salario': 92000, 'nivel': 'Senior'}

---
## 8. JSON → DataFrame con pandas

En la práctica, casi siempre convertimos JSON a DataFrame para analizar los datos.

In [29]:
import pandas as pd

# Lista de objetos → DataFrame directamente
df = pd.DataFrame(empleados)

df.head()

   id         nombre departamento  salario   nivel
0   1     Ana Torres       Ventas    92000  Senior
1   2  Bruno Sánchez   Tecnología   155000    Semi
2   3   Carla Méndez         RRHH    78000  Junior
3   4    Diego López     Finanzas   130000  Senior
4   5     Elena Ríos   Tecnología   175000  Senior

In [31]:
# También desde el archivo JSON
df_archivo = pd.read_json('empleados.json')

df_archivo.head()

   id         nombre departamento  salario   nivel
0   1     Ana Torres       Ventas    92000  Senior
1   2  Bruno Sánchez   Tecnología   155000    Semi
2   3   Carla Méndez         RRHH    78000  Junior
3   4    Diego López     Finanzas   130000  Senior
4   5     Elena Ríos   Tecnología   175000  Senior

### 8.1 JSON anidado: `pd.json_normalize()`

Cuando el JSON tiene objetos anidados, `pd.DataFrame()` devuelve columnas con dicts. `json_normalize()` los aplana automáticamente.

In [32]:
empleados_anidados = [
    {
        "id": 1, "nombre": "Ana Torres",
        "puesto": {"titulo": "Gerente",   "departamento": "Ventas"},
        "salario": 92000
    },
    {
        "id": 2, "nombre": "Bruno Sánchez",
        "puesto": {"titulo": "Desarrollador", "departamento": "Tecnología"},
        "salario": 155000
    },
    {
        "id": 3, "nombre": "Carla Méndez",
        "puesto": {"titulo": "Analista",   "departamento": "RRHH"},
        "salario": 78000
    },
]

# Sin normalizar: columna 'puesto' contiene dicts
print("Sin normalizar:")
print(pd.DataFrame(empleados_anidados))

print()

# Con json_normalize: aplana el objeto 'puesto' con prefijo
df_norm = pd.json_normalize(empleados_anidados)
print("Normalizado:")
print(df_norm)

Sin normalizar:
   id         nombre                                             puesto  \
0   1     Ana Torres    {'titulo': 'Gerente', 'departamento': 'Ventas'}
1   2  Bruno Sánchez  {'titulo': 'Desarrollador', 'departamento': 'T...
2   3   Carla Méndez     {'titulo': 'Analista', 'departamento': 'RRHH'}

   salario
0    92000
1   155000
2    78000

Normalizado:
   id         nombre  salario  puesto.titulo puesto.departamento
0   1     Ana Torres    92000        Gerente              Ventas
1   2  Bruno Sánchez   155000  Desarrollador          Tecnología
2   3   Carla Méndez    78000       Analista                RRHH

---
## 9. JSON vs XML

El mismo empleado representado en ambos formatos:

In [33]:
# El mismo dato: JSON vs XML

json_ejemplo = json.dumps({
    "id": 1,
    "nombre": "Ana Torres",
    "departamento": "Ventas",
    "salario": 92000,
    "habilidades": ["negociación", "CRM"]
}, ensure_ascii=False, indent=2)

xml_ejemplo = """<empleado>
  <id>1</id>
  <nombre>Ana Torres</nombre>
  <departamento>Ventas</departamento>
  <salario>92000</salario>
  <habilidades>
    <habilidad>negociación</habilidad>
    <habilidad>CRM</habilidad>
  </habilidades>
</empleado>"""

print(f"JSON ({len(json_ejemplo)} caracteres):")
print(json_ejemplo)
print()
print(f"XML ({len(xml_ejemplo)} caracteres):")
print(xml_ejemplo)

print(f"\nJSON es {len(xml_ejemplo)/len(json_ejemplo):.1f}x más compacto que XML en este ejemplo")

JSON (140 caracteres):
{
  "id": 1,
  "nombre": "Ana Torres",
  "departamento": "Ventas",
  "salario": 92000,
  "habilidades": [
    "negociación",
    "CRM"
  ]
}

XML (233 caracteres):
<empleado>
  <id>1</id>
  <nombre>Ana Torres</nombre>
  <departamento>Ventas</departamento>
  <salario>92000</salario>
  <habilidades>
    <habilidad>negociación</habilidad>
    <habilidad>CRM</habilidad>
  </habilidades>
</empleado>

JSON es 1.7x más compacto que XML en este ejemplo